/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jswing_calculadora;

/**
 *
 * @author samue
 */
public class Calculadora extends javax.swing.JFrame {
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        boton_resta = new javax.swing.JButton();
        boton_suma = new javax.swing.JButton();
        boton_dividir = new javax.swing.JButton();
        boton_CE = new javax.swing.JButton();
        boton_8 = new javax.swing.JButton();
        boton_9 = new javax.swing.JButton();
        boton_7 = new javax.swing.JButton();
        boton_C = new javax.swing.JButton();
        boton_2 = new javax.swing.JButton();
        boton_3 = new javax.swing.JButton();
        boton_1 = new javax.swing.JButton();
        boton_0 = new javax.swing.JButton();
        boton_5 = new javax.swing.JButton();
        boton_6 = new javax.swing.JButton();
        boton_4 = new javax.swing.JButton();
        boton_resultado = new javax.swing.JButton();
        boton_decimal = new javax.swing.JButton();
        boton_multi = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        boton_resta.setBackground(new java.awt.Color(51, 51, 51));
        boton_resta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_resta.setForeground(new java.awt.Color(255, 255, 255));
        boton_resta.setText("-");

        boton_suma.setBackground(new java.awt.Color(51, 51, 51));
        boton_suma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_suma.setForeground(new java.awt.Color(255, 255, 255));
        boton_suma.setText("+");
        boton_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sumaActionPerformed(evt);
            }
        });

        boton_dividir.setBackground(new java.awt.Color(51, 51, 51));
        boton_dividir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_dividir.setForeground(new java.awt.Color(255, 255, 255));
        boton_dividir.setText("/");
        boton_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_dividirActionPerformed(evt);
            }
        });

        boton_CE.setBackground(new java.awt.Color(51, 51, 51));
        boton_CE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_CE.setForeground(new java.awt.Color(255, 255, 255));
        boton_CE.setText("CE");
        boton_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CEActionPerformed(evt);
            }
        });

        boton_8.setBackground(new java.awt.Color(102, 102, 102));
        boton_8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_8.setForeground(new java.awt.Color(255, 255, 255));
        boton_8.setText("8");
        boton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_8ActionPerformed(evt);
            }
        });

        boton_9.setBackground(new java.awt.Color(102, 102, 102));
        boton_9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_9.setForeground(new java.awt.Color(255, 255, 255));
        boton_9.setText("9");

        boton_7.setBackground(new java.awt.Color(102, 102, 102));
        boton_7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_7.setForeground(new java.awt.Color(255, 255, 255));
        boton_7.setText("7");

        boton_C.setBackground(new java.awt.Color(51, 51, 51));
        boton_C.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_C.setForeground(new java.awt.Color(255, 255, 255));
        boton_C.setText("C");

        boton_2.setBackground(new java.awt.Color(102, 102, 102));
        boton_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_2.setForeground(new java.awt.Color(255, 255, 255));
        boton_2.setText("2");

        boton_3.setBackground(new java.awt.Color(102, 102, 102));
        boton_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_3.setForeground(new java.awt.Color(255, 255, 255));
        boton_3.setText("3");

        boton_1.setBackground(new java.awt.Color(102, 102, 102));
        boton_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_1.setForeground(new java.awt.Color(255, 255, 255));
        boton_1.setText("1");
        boton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_1ActionPerformed(evt);
            }
        });

        boton_0.setBackground(new java.awt.Color(102, 102, 102));
        boton_0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_0.setForeground(new java.awt.Color(255, 255, 255));
        boton_0.setText("0");

        boton_5.setBackground(new java.awt.Color(102, 102, 102));
        boton_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_5.setForeground(new java.awt.Color(255, 255, 255));
        boton_5.setText("5");

        boton_6.setBackground(new java.awt.Color(102, 102, 102));
        boton_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_6.setForeground(new java.awt.Color(255, 255, 255));
        boton_6.setText("6");

        boton_4.setBackground(new java.awt.Color(102, 102, 102));
        boton_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_4.setForeground(new java.awt.Color(255, 255, 255));
        boton_4.setText("4");

        boton_resultado.setBackground(new java.awt.Color(153, 0, 153));
        boton_resultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_resultado.setForeground(new java.awt.Color(255, 255, 255));
        boton_resultado.setText("=");
        boton_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_resultadoActionPerformed(evt);
            }
        });

        boton_decimal.setBackground(new java.awt.Color(102, 102, 102));
        boton_decimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_decimal.setForeground(new java.awt.Color(255, 255, 255));
        boton_decimal.setText(",");

        boton_multi.setBackground(new java.awt.Color(51, 51, 51));
        boton_multi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_multi.setForeground(new java.awt.Color(255, 255, 255));
        boton_multi.setText("*");
        boton_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_multiActionPerformed(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setBackground(new java.awt.Color(204, 204, 204));
        resultado.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 0, 0));
        resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultado.setText("jTextField2");
        resultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(boton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(boton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(boton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boton_CE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boton_C, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boton_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(resultado)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_C, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_dividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_dividirActionPerformed

    private void boton_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_sumaActionPerformed

    private void boton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_8ActionPerformed

    private void boton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_1ActionPerformed

    private void boton_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_multiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_multiActionPerformed

    private void boton_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CEActionPerformed
        // TODO add your handling code here:
        CalculadoraController.manejarEvento(evt.getActionCommand());
    }//GEN-LAST:event_boton_CEActionPerformed

    private void boton_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_resultadoActionPerformed
        // TODO add your handling code here:
        String resultado1="aaa";
        resultado.setText(resultado1);
    }//GEN-LAST:event_boton_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_0;
    private javax.swing.JButton boton_1;
    private javax.swing.JButton boton_2;
    private javax.swing.JButton boton_3;
    private javax.swing.JButton boton_4;
    private javax.swing.JButton boton_5;
    private javax.swing.JButton boton_6;
    private javax.swing.JButton boton_7;
    private javax.swing.JButton boton_8;
    private javax.swing.JButton boton_9;
    private javax.swing.JButton boton_C;
    private javax.swing.JButton boton_CE;
    private javax.swing.JButton boton_decimal;
    private javax.swing.JButton boton_dividir;
    private javax.swing.JButton boton_multi;
    private javax.swing.JButton boton_resta;
    private javax.swing.JButton boton_resultado;
    private javax.swing.JButton boton_suma;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
